### ISSUE TITLE
iOS версия крашится в релизной сборке когда ее заливаешь в Apple Connect

### ISSUE THREAD

**Issue by fufylev** [yandex/yandex_maps_mapkit#11]
В дебаг режиме сборка с картами все работает отлично, но именно в сборке которая залита в AppStore  приложение запускается с черным экраном и через консоль в xCode вот такую ошибку кидает флаттер

Версия:  flutter 3.22.0
```dart
environment:
  sdk: '>=3.4.3 <4.0.0'
...
yandex_maps_mapkit: ^4.7.2-beta6
```

```dart
Invalid argument(s): Failed to lookup symbol 'yandex_maps_flutter_is_init': dlsym(RTLD_DEFAULT, yandex_maps_flutter_is_init): symbol not found
```

Код стартует вот так:
```dart
...
WidgetsFlutterBinding.ensureInitialized();

await init.initMapkit(apiKey: '589cb9b1-bb9f-4235-a08f-.............'); // ключ скрыт на всякий случай
```

**Comment by fufylev** [comment]
аналогичный кейс 
[https://github.com/yandex/yandex_maps_mapkit_lite/issues/13](https://github.com/yandex/yandex_maps_mapkit_lite/issues/13)

**Comment by gle6ru381** [comment]
https://docs.flutter.dev/platform-integration/ios/c-interop#stripping-ios-symbols

**Comment by fufylev** [comment]
> https://docs.flutter.dev/platform-integration/ios/c-interop#stripping-ios-symbols

Спасибо! Баг пропал

**Comment by blosser** [comment]
[main.txt](https://github.com/user-attachments/files/22646089/main.txt)
