### ISSUE TITLE
Карта отображается как сетка вместо ожидаемого вида, даже с платным API-ключом

### ISSUE THREAD

**Issue by aibekdv** [yandex/yandex_maps_mapkit#14]
Здравствуйте,

Столкнулся с проблемой, при которой проект, ранее работавший без каких-либо проблем, теперь перестал функционировать корректно. Даже после переключения на действующий платный API-ключ, карта не отображается должным образом. Ниже приведены подробности:

**Проблема:**
  - Приложение загружается, но вместо ожидаемого отображения карты показывается сетчатый узор.
  - Ошибки в логах отсутствуют.
  - Ранее эта же конфигурация работала идеально.

**Шаги для воспроизведения:**
  - Запустить приложение.
  - Перейти на экран с картой.
  - Увеличить масштаб или переместить карту.

**Ожидаемое поведение:**
  - Карта должна загружаться и отображаться корректно.

**Фактическое поведение:**
  - Вместо карты отображается сетчатый узор.
  - Интерактивный пользовательский интерфейс и визуализация не работают как ожидалось.

**Что я пробовал:**
  - Проверил, что API-ключ Yandex MapKit установлен правильно.
  - Проверил наличие интернет-соединения (проблем не обнаружено).
  - Обновил пакет `yandex_mapkit` до последней версии.
  - Очистил кэш проекта с помощью команды `flutter clean` и переустановил зависимости.
  - Проверил наличие необходимых разрешений в `AndroidManifest.xml` и `Info.plist`.
  - Протестировал приложение на нескольких устройствах и в разных окружениях (как на эмуляторе, так и на реальном устройстве).

**Окружение:**
  - Версия Yandex MapKit: [ 4.1.0]
  - Версия Flutter: [3.24.4]
  - Платформа: [Android/iOS]

**Дополнительная информация:**
  - Проблема сохраняется даже при использовании платного API-ключа.
  - В логах отсутствуют ошибки, что затрудняет процесс отладки.
  - Эта же конфигурация раньше работала без каких-либо проблем.

Спасибо за внимание, надеюсь на вашу помощь в решении этой проблемы.

**Comment by fufylev** [comment]
> Здравствуйте,
> 
> Столкнулся с проблемой, при которой проект, ранее работавший без каких-либо проблем, теперь перестал функционировать корректно. Даже после переключения на действующий платный API-ключ, карта не отображается должным образом. Ниже приведены подробности:
> 
> **Проблема:**
> 
> * Приложение загружается, но вместо ожидаемого отображения карты показывается сетчатый узор.
> * Ошибки в логах отсутствуют.
> * Ранее эта же конфигурация работала идеально.
> 
> **Шаги для воспроизведения:**
> 
> * Запустить приложение.
> * Перейти на экран с картой.
> * Увеличить масштаб или переместить карту.
> 
> **Ожидаемое поведение:**
> 
> * Карта должна загружаться и отображаться корректно.
> 
> **Фактическое поведение:**
> 
> * Вместо карты отображается сетчатый узор.
> * Интерактивный пользовательский интерфейс и визуализация не работают как ожидалось.
> 
> **Что я пробовал:**
> 
> * Проверил, что API-ключ Yandex MapKit установлен правильно.
> * Проверил наличие интернет-соединения (проблем не обнаружено).
> * Обновил пакет `yandex_mapkit` до последней версии.
> * Очистил кэш проекта с помощью команды `flutter clean` и переустановил зависимости.
> * Проверил наличие необходимых разрешений в `AndroidManifest.xml` и `Info.plist`.
> * Протестировал приложение на нескольких устройствах и в разных окружениях (как на эмуляторе, так и на реальном устройстве).
> 
> **Окружение:**
> 
> * Версия Yandex MapKit: [ 4.1.0]
> * Версия Flutter: [3.24.4]
> * Платформа: [Android/iOS]
> 
> **Дополнительная информация:**
> 
> * Проблема сохраняется даже при использовании платного API-ключа.
> * В логах отсутствуют ошибки, что затрудняет процесс отладки.
> * Эта же конфигурация раньше работала без каких-либо проблем.
> 
> Спасибо за внимание, надеюсь на вашу помощь в решении этой проблемы.

Версия Yandex MapKit: [ 4.1.0] - такой версии нету в данном пакете - вы точно в правильный репозиторий написали? такая версия есть только в пакете https://pub.dev/packages/yandex_mapkit но это совершенно другой пакет

**Comment by aibekdv** [comment]
Проблема решилась спустя несколько часов. Она была связана с работой серверов Яндекса, а не с самим пакетом.
